### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by a-azdad** [a-azdad/Runescape-Map-Viewer#9]
We could port the runelite opengl plugin
See: https://github.com/runelite/runelite/tree/73d928ea8928d9384656d99714b7761239fed505/runelite-client/src/main/java/net/runelite/client/plugins/gpu
The API that calls to the runescape client should be edited to load from our modules

**Comment by Printf-Jung** [comment]
1. Remove lombok for getters and setters where needed
2. Replace the Runelite Plugin Configuration functionality for a configuration.java file
3. Add the required dependencies
4. Merge the Runelite Constant class required variables with the created configuration.java file
5. Figure out all the API naming in comparison to the naming used in the Client used

**Comment by Printf-Jung** [comment]
API's Used in SceneUploader.java

Runelite -- Client
import net.runelite.api.DecorativeObject;    com.runescape.scene.object.GroundDecoration;
import net.runelite.api.GameObject;           com.runescape.entity.GameObject;
import net.runelite.api.GroundObject;         Not needed for a mapviewer (items..etc.)
import net.runelite.api.Model;                     com.runescape.entity.model.Model;
import net.runelite.api.Perspective;            Potentially com.runescape.scene.Scenegraph
import net.runelite.api.Point;                       ?? Inherited by Perspective
import net.runelite.api.Renderable;            com.runescape.entity.Renderable;
import net.runelite.api.Scene;                    com.runescape.scene.MapRegion;
import net.runelite.api.SceneTileModel;      ??MapRegion
import net.runelite.api.SceneTilePaint;        ??MapRegion
import net.runelite.api.Tile;                              com.runescape.scene.object.tile.Tile;
import net.runelite.api.WallObject;                   com.runescape.scene.object.WallObject;

Equals

**Comment by Printf-Jung** [comment]
API's Used in TextureManager.java

Runelite -- Client
**import net.runelite.api.Texture;**  
**import net.runelite.api.TextureProvider;**
